-- CreateTable
CREATE TABLE `Proveedor` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `INS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(191) NOT NULL,
    `fecha_contrato` DATETIME(3) NOT NULL,
    `id_proveedor` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CAMBIOS_APLICADOS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fecha_act` DATETIME(3) NOT NULL,
    `observaciones` VARCHAR(191) NULL,
    `creado` DATETIME(3) NOT NULL,
    `actualizado` DATETIME(3) NOT NULL,
    `id_version` INTEGER NOT NULL,
    `id_ins` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `VERSIONES` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DETALLE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `texto` VARCHAR(191) NOT NULL,
    `scripts` VARCHAR(191) NOT NULL,
    `instrucciones` VARCHAR(191) NOT NULL,
    `id_version` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `INS` ADD CONSTRAINT `INS_id_proveedor_fkey` FOREIGN KEY (`id_proveedor`) REFERENCES `Proveedor`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CAMBIOS_APLICADOS` ADD CONSTRAINT `CAMBIOS_APLICADOS_id_version_fkey` FOREIGN KEY (`id_version`) REFERENCES `VERSIONES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CAMBIOS_APLICADOS` ADD CONSTRAINT `CAMBIOS_APLICADOS_id_ins_fkey` FOREIGN KEY (`id_ins`) REFERENCES `INS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETALLE` ADD CONSTRAINT `DETALLE_id_version_fkey` FOREIGN KEY (`id_version`) REFERENCES `VERSIONES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
